name: firstflow
on:
 push:
   branches:
   - main
jobs:
 example-jobs:
   runs-on: ubuntu:latest

   steps:
     - name: print a welcome message
       run: echo "Welcome to our first Github Actions workflow"
   
   
   
