on: 
  workflow_dispatch: 
    inputs:
      environment:
        description: "choose envionment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
        

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy aaplication
        run: echo "Deploying the application"
