on:
  push:
    branches:
    - main
    - "release/xx" #anything after release
    paths:
      - "src/xx"  #to aviod run the pipeline on all the repository files as maybe i have documentation files so to avoid that i can identify specifc paths

  pull_request:
    branches:
    - main
    - "release/xx" #anything after release

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
   - name: checkout code
   - uses: actions/checkout@4.2.2
   - name: run tests
     run: npm test

   
    
